export const RESET_APP_START = 'RESET_APP_START';
export const RESET_APP = 'RESET_APP';
export const RESET_APP_SUCCESS = 'RESET_APP_SUCCESS';
export const RESET_APP_FAILURE = 'RESET_APP_FAILURE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REQUEST_RESET_START = 'REQUEST_RESET_START';
export const REQUEST_RESET_SUCCESS = 'REQUEST_RESET_SUCCESS';
export const REQUEST_RESET_FAILURE = 'REQUEST_RESET_FAILURE';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const RESEND_VERIFICATION_START = "RESEND_VERIFICATION_START";
export const RESEND_VERIFICATION_SUCCESS = "RESEND_VERIFICATION_SUCCESS";
export const RESEND_VERIFICATION_FAILURE = "RESEND_VERIFICATION_FAILURE";

export const LOGIN_2FA_START = "LOGIN_2FA_START";
export const LOGIN_2FA_SUCCESS = "LOGIN_2FA_SUCCESS";
export const LOGIN_2FA_FAILURE = "LOGIN_2FA_FAILURE";

export const REFRESH_TOKEN_START = "REFRESH_TOKEN_START";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE";

export const MOBILE_OTP_PROCESS_START = "MOBILE_OTP_PROCESS_START";
export const MOBILE_OTP_PROCESS_SUCCESS = "MOBILE_OTP_PROCESS_SUCCESS";
export const MOBILE_OTP_PROCESS_FAILURE = "MOBILE_OTP_PROCESS_FAILURE";
