export const RETRIEVE_STORIES_START = "RETRIEVE_STORIES_START";
export const RETRIEVE_STORIES_SUCCESS = "RETRIEVE_STORIES_SUCCESS";
export const RETRIEVE_STORIES_FAILURE = "RETRIEVE_STORIES_FAILURE";

export const RETRIEVE_CATEGORIES_START = "RETRIEVE_CATEGORIES_START";
export const RETRIEVE_CATEGORIES_FAILURE = "RETRIEVE_CATEGORIES_FAILURE";
export const RETRIEVE_CATEGORIES_SUCCESS = "RETRIEVE_CATEGORIES_SUCCESS";

export const RETRIEVE_STORY_START = "RETRIEVE_STORY_START";
export const RETRIEVE_STORY_FAILURE = "RETRIEVE_STORY_FAILURE";
export const RETRIEVE_STORY_SUCCESS = "RETRIEVE_STORY_SUCCESS";

export const RETRIEVE_CATEGORY_STORIES_START = "RETRIEVE_CATEGORY_STORIES_START";
export const RETRIEVE_CATEGORY_STORIES_SUCCESS = "RETRIEVE_CATEGORY_STORIES_SUCCESS";
export const RETRIEVE_CATEGORY_STORIES_FAILURE = "RETRIEVE_CATEGORY_STORIES_FAILURE";
