export const ROUTE_TRANSITION_START = 'ROUTE_TRANSITION_START';
export const ROUTE_TRANSITION_COMPLETE = 'ROUTE_TRANSITION_COMPLETE';
export const ROUTE_TRANSITION_FAILURE = 'ROUTE_TRANSITION_FAILURE';
