export const SHOW_TOAST_START = 'SHOW_TOAST_START';
export const SHOW_TOAST_COMPLETE = 'SHOW_TOAST_COMPLETE';
export const MANUALLY_DISMISS_TOAST = 'MANUALLY_DISMISS_TOAST';
export const ADD_TOAST = 'ADD_TOAST';
export const ASSIGN_TO_DISMISS = 'ASSIGN_TO_DISMISS';
