export const EXTEND_INACTIVITY = 'EXTEND_INACTIVITY';
export const PAUSE_INACTIVITY = 'PAUSE_INACTIVITY';
export const RESUME_INACTIVITY = 'RESUME_INACTIVITY';
export const ClEAR_INACTIVITY = 'ClEAR_INACTIVITY';
export const ADD_BASE_TIME = 'ADD_BASE_TIME';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const CLEAR_ACTIVITY = 'CLEAR_ACTIVITY';